name: birblogger
main: com.birbnest.birblogger.Plugin
version: 0.0.1
api-version: 1.15
commands:
  birblogger:
    description: Changes logging to true or false
    usage: /birblogger
  broadcast:
    description: Broadcasts a message
    usage: /broadcast <message>
permissions:
  birblogger.broadcast:
    description: For broadcasting messages
    default: op
  birblogger.use:
    description: Allows the execution of birblogger
    default: op
